---
title: ""
author: "Aaron Peikert"
date: "11/30/2019"
output: html_document
---


# Event Title: 

Reproducible Research with R & RMarkdown [& tidyverse]

# Goal & Description

Motivating Students to use Rmarkdown and create the confidence to tackle simple explorative analyses.

# Detailed Description

* to be done

# Target Audience

* third semester psychologie students and above 

# Event Duration

* 2x3h

# Envisioned Number of Participants

* to be decided

# Planning / How-To:
* start with new Markdown
* create graphics with movies dataset
* let people debug some examples
* present opensource philosophie


# Required resources (money, materials, people, rooms)
* educational resource restricted to Slides + R4DS + Stackoverflow
* movie dataset
* projector
* Room with enough Power supplies
* miniCRAN
* Bier

# Planning before the event
to be done

## When and where do you get the required resources?
## What has to be organized before the event can take place?
## When and how could you advertise the event?

# To be Prepared by the founders

* Slidedeck with (Latex-)Beamer
* detailed Roadmap + guideline

# Planning the actual event

to be done

From (time)
To (time)
What?
Goal
Materials
Who?


# After the event

to be done

What has to be done after the event? (e.g., cleaning up, bringing back materials, …)
How do you keep in contact to your participants (if desired)?
How can learnings from this event be transferred to the next event?
Should the event be evaluated and if yes, how?



